# Generated by Django 2.2.5 on 2019-10-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Desc', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in progress', 'In Progress'), ('completed', 'Completed')], max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
            ],
        ),
    ]
