# Generated by Django 2.2.5 on 2019-10-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Desc',
            new_name='desc',
        ),
    ]
